### ISSUE TITLE
Missing school subjects

### ISSUE THREAD

**Issue by ElloWorld01** [itskatt/extracursus#4]
Hello,
I'm an english user of IntraCursus too. 😉 

Some friends in BUT QLIO noticed that some of their subjects did not appear.
Please find attached the pictures illustrating the situation.

Thank you for your consideration.

![extracursus](https://user-images.githubusercontent.com/69735084/215289533-cf89f854-9816-432e-a95a-dfc8b31f0751.png)
![pdf-intracursus](https://user-images.githubusercontent.com/69735084/215289532-12282d72-7ecb-4a04-9b18-38f178cd6389.png)

**Comment by itskatt** [comment]
Should be fixed
